/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ComputacaoG;

import javax.swing.JOptionPane;
import static java.lang.Math.sqrt;


/**
 *
 * @author izabela
 */
public class secondFrame extends javax.swing.JFrame{
     transf tran = transf.getInstance();
    int []vetX2 = new int[70];
    int []vetY2 = new int[70];
    int px =0 ;
    int py = 0;
    Janela j;
    boolean estado= false ;
    public secondFrame(boolean e) {
        estado = e;
        initComponents();
    }
    public void instancia(){
        estado = true;
        this.setAlwaysOnTop(true);
        j= new Janela(vetX2,vetY2,1);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtrans = new javax.swing.JTextField();
        jTxesc = new javax.swing.JTextField();
        jTangulo = new javax.swing.JTextField();
        jTytrans = new javax.swing.JTextField();
        jTyesc = new javax.swing.JTextField();
        btnTrans = new javax.swing.JButton();
        btnEsc = new javax.swing.JButton();
        btnRot = new javax.swing.JButton();
        btnReflexao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTprX = new javax.swing.JTextField();
        jTprY = new javax.swing.JTextField();
        jTrefleteX = new javax.swing.JCheckBox();
        jTrefleteY = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        jRadioButton1.setText("jRadioButton1");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Opções para transformadas: ");

        jLabel2.setText("Translação :");

        jLabel3.setText("Rotação :");

        jLabel4.setText("Escala :");

        jLabel5.setText("Reflexão:");

        jTxtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtransActionPerformed(evt);
            }
        });

        jTxesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxescActionPerformed(evt);
            }
        });

        jTangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTanguloActionPerformed(evt);
            }
        });

        jTytrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTytransActionPerformed(evt);
            }
        });

        jTyesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTyescActionPerformed(evt);
            }
        });

        btnTrans.setText("OK");
        btnTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransActionPerformed(evt);
            }
        });

        btnEsc.setText("OK");
        btnEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscActionPerformed(evt);
            }
        });

        btnRot.setText("OK");
        btnRot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotActionPerformed(evt);
            }
        });

        btnReflexao.setText("OK");
        btnReflexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReflexaoActionPerformed(evt);
            }
        });

        jLabel6.setText("RefX :");

        jLabel7.setText("RefY:");

        jTprY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTprYActionPerformed(evt);
            }
        });

        jTrefleteX.setText("x");
        jTrefleteX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrefleteXActionPerformed(evt);
            }
        });

        jTrefleteY.setText("y");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("As cores do plano Cartesiano:");

        jLabel10.setText("*Azul  - Pontos Digitados");

        jLabel11.setText("*Vermelho  Pontos Transformados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtrans, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                        .addComponent(jTxesc))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTytrans)
                                        .addComponent(jTyesc, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)))
                                .addComponent(jTangulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTrefleteX)
                                .addGap(57, 57, 57)
                                .addComponent(jTrefleteY)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnReflexao)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEsc)
                                            .addComponent(btnTrans))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(jLabel11))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTprY))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTprX, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTytrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrans)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTyesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEsc)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnRot)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnReflexao)
                    .addComponent(jTrefleteX)
                    .addComponent(jTrefleteY))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTprX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTprY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtransActionPerformed

    private void jTxescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxescActionPerformed
    private void jTanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTanguloActionPerformed
    private void jTytransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTytransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTytransActionPerformed
    private void jTyescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTyescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTyescActionPerformed
    private void btnTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransActionPerformed
         try{
            //este botão é utilizado para armazenar o resultado das translaçoes feitas 
            // utilizando para isso, o vetor vetX2 e vetY2
            int a =Integer.parseInt(jTxtrans.getText());
            int b =Integer.parseInt(jTytrans.getText());
            for(int i=0; i < tran.contador; i++){
                vetX2[i]= a + tran.vetX[i];
                vetY2[i]= b + tran.vetY[i]; 
            }
            if(!estado){  
              instancia();  
            } else{
              j.conf();
              estado = false;
              instancia();
            }  
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Coordenadas inválidas na segunda ");
        }          
    }//GEN-LAST:event_btnTransActionPerformed
    private void btnEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscActionPerformed
      
            try{
            //este botão é utlizado para armazenar o resultado da escala feita
            //sobre os pontos digitados, para isso utiliza-se o vetor vetX2 e vetY2
            px = Integer.parseInt(jTprX.getText());
            py = Integer.parseInt(jTprY.getText());
            int a = Integer.parseInt(jTxesc.getText());
            int b = Integer.parseInt(jTyesc.getText());
            if(px ==0 && py==0){
                for(int j =0; j < tran.contador;j++){
                   vetX2[j] = a * tran.vetX[j];
                   vetY2[j] = b * tran.vetY[j];
                }
                if(!estado){
                    instancia();
                }else{
                    j.conf();
                    instancia();
                }
            }
            else{
                int transladaX = 0 - (px);
                int transladaY = 0 - (py);
                for(int k =0 ; k < tran.contador;k++){
                    vetX2[k] = tran.vetX[k] + (transladaX);
                    vetY2[k]=  tran.vetY[k] + (transladaY);      
                }
                // apos transladar fazer operaçao
                for(int l =0; l < tran.contador; l++){
                    vetX2[l] = vetX2[l] * a;
                    vetY2[l] =vetY2[l] * b ;
                }
                for(int h =0 ; h < tran.contador;h++){
                    vetX2[h]= vetX2[h] +(-transladaX);
                    vetY2[h] = vetY2[h]+(-transladaY);       
                }
                 if(!estado){
                    instancia();
                }else{
                    j.conf();
                    instancia();
                }
            }
        }catch(Exception e){
              JOptionPane.showMessageDialog(null, "Erro, tente pontos de referência");
        }
    }//GEN-LAST:event_btnEscActionPerformed
    public int arred(double a ){
         String m =""+a;
        String h ="";
        int resp=0;   
	for(int g = 0; g < m.length(); g++){
            if(m.charAt(g) =='.'){
                int b = Integer.parseInt(""+m.charAt(g+1));
                if(b >5 || b ==5){
                    resp = Integer.parseInt(h);
                    if( h.charAt(0) == '-' ){
                        resp = resp -1;
                    }
                    else{
                        resp = resp +1;
                    }
                }
                else {
                    resp = Integer.parseInt(h); 
                }
            }
            h = h +m.charAt(g); 
        }
        return resp;
}
    private void btnRotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotActionPerformed
      
          try{
            Double cos = Math.cos(Double.parseDouble(jTangulo.getText()));
            Double sen =  Math.sin(Double.parseDouble(jTangulo.getText()));
            Double a=0.0; 
            Double b=0.0; 
            px = Integer.parseInt(jTprX.getText());
            py = Integer.parseInt(jTprY.getText());
            if(px ==0 && py==0){
                for(int k=0; k < tran.contador;k++){
                    a = tran.vetX[k]*cos - tran.vetY[k]*sen; 
                    b = tran.vetX[k]*sen+ tran.vetY[k]*cos;
                    vetX2[k] = arred(a);
                    vetY2[k] = arred(b);         
                }
                 if(!estado){
                    instancia();
                }else{
                    j.conf();
                    instancia();
                }
            }
            else{
                int transladaX = 0 - (px);
                int transladaY = 0 - (py);
                for(int k =0 ; k < tran.contador;k++){
                    vetX2[k] = tran.vetX[k] + (transladaX);
                    vetY2[k]=  tran.vetY[k] + (transladaY);  
                }
                for(int k=0; k < tran.contador;k++){
                    a = vetX2[k]*cos - vetY2[k]*sen; 
                    b = vetX2[k]*sen + vetY2[k]*cos;
                    vetX2[k] = arred(a);
                    vetY2[k] = arred(b);  
                }
                for(int h =0 ; h < tran.contador;h++){
                    vetX2[h]= vetX2[h] +(-transladaX);
                    vetY2[h] = vetY2[h]+(-transladaY);   
                }
                
                 if(!estado){
                    instancia();
                }else{
                    j.conf();
                    instancia();
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro, tente pontos de referência");
        }
    }//GEN-LAST:event_btnRotActionPerformed
    private void btnReflexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReflexaoActionPerformed
       if(jTrefleteX.isSelected()== true && jTrefleteY.isSelected()==true){
            for(int g =0; g < tran.contador; g++){
                vetX2[g]= (-1) *( tran.vetX[g]);
                vetY2[g]= (-1) *( tran.vetY[g]);
            }
               if(!estado){
                    instancia();
                }else{
                    j.conf();
                    instancia();
                }
        }
        else if(jTrefleteX.isSelected()!= true && jTrefleteY.isSelected()==true){
            for(int g =0; g < tran.contador; g++){
                vetX2[g]= (-1) *( tran.vetX[g]);
                vetY2[g]= ( tran.vetY[g]);             
            }  
               if(!estado){
                    instancia();
                }else{
                    j.conf();
                    instancia();
                }
        }
        else if(jTrefleteX.isSelected()== true && jTrefleteY.isSelected()!=true ){
            for(int g =0; g < tran.contador; g++){
                vetX2[g]= ( tran.vetX[g]);
                vetY2[g]= (-1)*( tran.vetY[g]);  
            }  
               if(!estado){
                    instancia();
                }else{
                    j.conf();
                    instancia();
                }
        }   
       
    }//GEN-LAST:event_btnReflexaoActionPerformed
    private void jTprYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTprYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTprYActionPerformed
    private void jTrefleteXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrefleteXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTrefleteXActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        fec();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void fec(){
        vetX2=null;
        vetX2 = new int[70];
        vetY2=null;
        vetY2 = new int[70];
        tran.vetX = null;
        tran.vetX = new int[70];
        tran.vetY = null;
        tran.vetY = new int[70];
       
        j.conf();
        this.dispose();
        new transf().setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                new secondFrame(false).setVisible(true);
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsc;
    private javax.swing.JButton btnReflexao;
    private javax.swing.JButton btnRot;
    private javax.swing.JButton btnTrans;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTangulo;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTprX;
    private javax.swing.JTextField jTprY;
    private javax.swing.JCheckBox jTrefleteX;
    private javax.swing.JCheckBox jTrefleteY;
    private javax.swing.JTextField jTxesc;
    private javax.swing.JTextField jTxtrans;
    private javax.swing.JTextField jTyesc;
    private javax.swing.JTextField jTytrans;
    // End of variables declaration//GEN-END:variables
}
